
FROM rasa/rasa:3.6.10

COPY . /app
WORKDIR /app

COPY requirements.txt ./
RUN python -m pip install --upgrade pip setuptools wheel
RUN pip install -r requirements.txt

CMD ["run", "--enable-api", "--cors", "*", "--debug"]
